services:
  - type: web
    name: taskflow-ai
    plan: starter
    runtime: node
    
    repo: https://github.com/SEU-USUARIO/SEU-REPO
    branch: main
    
    buildCommand: chmod +x start.sh && cd backend && pip install -r requirements.txt && cd ../frontend && npm install && npm run build
    
    startCommand: ./start.sh
    
    envVars:
      - key: DATABASE_CLOUD_URL
        scope: run
      - key: SECRET_KEY
        scope: run
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
    
    healthCheckPath: /api/v1/health
    healthCheckInterval: 300
